app:
  database: "taaja"


kafka:
  bootstrap-servers: "46.101.136.244:9092"
  poll-records: 100
  auto-commit: false
  offset-reset: "latest"
  group-id: "redcat"

  prefix:
    zone: "zone"
    vehicle-data: "vehicle-data"


quarkus:
  swagger-ui:
    always-include: true
  http:
    port: 8092
    cors: true
  mongodb:
    connection-string: mongodb://taaja-mongodb:27017

purple-tiger:
  url: "https://purpletiger.taaja.io//v1/calculate/intersectingExtensions"

"%dev":
  app:
    database: "dev-taaja"

  quarkus:
    swagger-ui:
      always-include: true
    mongodb:
      connection-string: mongodb://localhost:27017

  purple-tiger:
    url: "http://localhost:8093/v1/calculate/intersectingExtensions"

"%test":
  app:
    database: "test-taaja"

  quarkus:
    mongodb:
      connection-string: mongodb://localhost:27017
