app:
  database: "taaja"


kafka:
  bootstrap-servers: "136.243.131.9:9092"
  poll-records: 100
  auto-commit: true
  offset-reset: "earliest"
  group-name: "redcat"

quarkus:
  swagger-ui:
    always-include: true
  http:
    port: 8092
    cors: true
  mongodb:
    connection-string: mongodb://taaja-mongodb:27017
  log:
    handler:
      gelf:
        enabled: true
        #host: log.kara-software.at
        host: 10.0.0.1
#        host: 188.68.52.208
        port: 12201

services.purple-tiger:
  timeout: 3000
  url: "https://purpletiger.taaja.io"

"%dev":
  kafka:
    bootstrap-servers: "193.26.156.80:9092"

  app:
    database: "dev-taaja"

  quarkus:
    swagger-ui:
      always-include: true
    mongodb:
      connection-string: mongodb://localhost:27017

  services.purple-tiger:
    url: "http://localhost:8093"

"%test":
  app:
    database: "test-taaja"

  quarkus:
    mongodb:
      connection-string: mongodb://localhost:27017
