app:
  database: "taaja"


kafka:
  bootstrap-servers: "46.101.136.244:9092"
  poll-records: 100
  auto-commit: false
  offset-reset: "latest"
  group-id: "redcat"

quarkus:
  swagger-ui:
    always-include: true
  http:
    port: 8092
    cors: true
  mongodb:
    connection-string: mongodb://taaja-mongodb:27017

services.purple-tiger:
  timeout: 3000
  url: "https://purpletiger.taaja.io"

"%dev":
  app:
    database: "dev-taaja"

  quarkus:
    swagger-ui:
      always-include: true
    mongodb:
      connection-string: mongodb://localhost:27017

  services.purple-tiger:
    url: "http://localhost:8093"

"%test":
  app:
    database: "test-taaja"

  quarkus:
    mongodb:
      connection-string: mongodb://localhost:27017
